### ISSUE TITLE
English / 英语

### ISSUE THREAD

**Issue by AlphaHot** [cnrv/home#149]
Hello everyone, who can translate all the materials into English? Translate please, English is an international language. Write everything in English.
---
大家好，谁可以把所有的材料翻译成英文？ 请翻译，英语是国际语言。 用英语写一切。

**Comment by wsong83** [comment]
At the very top of the home page, it reads

> 本站点希望能够为国内的RISC-V开发者和爱好者提供便利。

I assume all RISC-V lovers inside China probably understand Chinese and most of them prefer, although unideal indeed, Chinese. If everything should be in English just because it is an international language, most content in this website seems useless as it is originally in English and translated to Chinese here.
