### ISSUE TITLE
risc-v conference的資料要放在resource.md嗎？

### ISSUE THREAD

**Issue by poweihuang17** [cnrv/home#54]
還不確定我有沒有時間弄這個，不過先丟在這邊備著。
https://riscv.tokyo/2017/presentation-downloads/

**Comment by wsong83** [comment]
I do not think so because we did not put any workshop presentation, or even the papers from CARRV into resource.md. My reasoning is: one, presentations, papers are not really resources immediately useful compared with the items in resoruce.md, and two, if we start to do this, this will be a huge burden to trace all workshops and cofnerences.

Besides, we already have a paper page to record RISC-V related papers.

**Comment by wsong83** [comment]
By another thought, my objection might not be that strong.
They are still potential useful to track somewhere.
So we can add a new section in the resoruce.md such as "pass events" and record this type of resource there. If you decide to do this, I think it would better to back-trace the pass event in last two years, including RISC-V workshops, ORConf, and CARRV.

**Comment by poweihuang17** [comment]
我覺得對我來說最大的問題在於bandwidth不夠，還不確定他意義有多大。所以也只是先擺著。就像donation link一樣 : )

**Comment by poweihuang17** [comment]
因為bandwidth不夠，先把這個close。
